# workflow's name
name: "Build and deploy Github pages"

# Événements sur lesquels il doit être déclenché
on:
  push:         # <- Déclenché lorsque l'on pousse du code...
    branches:
      - master  # <- ... mais seulement sur la branche "master"

jobs:

  # Notre job
  build-and-deploy:
    runs-on: ubuntu-latest

    # Tâches à effectuer :
    steps:

      # 1. On récupère le contenu du dépôt

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 2. On installe l'environnement conda des dev
      # cf. fichier readme du dépôt rpviz
      # mettre dans base car variables non-persistantes
      - name: "Set up conda environment"
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-activate-base: true
          activate-environment: ""
          environment-file: environment.yaml

      # 2. Partie spécifique à Sphinx (installation des
      #    dépendances et génération de la doc)

      - name: "Install Python dependencies"
        run: |
          pip3 install sphinx sphinx-rtd-theme
          pip3 install --upgrade myst-parser

      - name: "Build Sphinx Doc"
        run: |
          cd docsource
          make html

      # 3. Déploiement sur les Github Pages

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages     # <- Branche sur laquelle seront commités les fichiers
          FOLDER: ../docsource/_build/html/  # <- Dossier contenant notre documentation générée
